name: Refresh charts

on:
  schedule:
    # - cron: '*/5 * * * *' # Every 5 minutes
    - cron: '0 10 * * *' # Every day at 10 am in the morning
  workflow_dispatch:

jobs:
  refresh-charts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'gh-actions-update'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Cache Python environment
      id: cache-python-env
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt', '**/.python-version') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Install Python environment
      if: steps.cache-python-env.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    - name: Run project code
      run: |
        source .venv/bin/activate
        doit
        cp -r ./docs/_build/html/* ./docs/
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actor
        add: 'docs/* --force'
        new_branch: gh-actions-update
        pull: 'origin gh-actions-update --rebase --autostash'
        push: 'origin gh-actions-update --force'